# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/python:3.8

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker Image
          command: | 
            docker build -t $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1} .

      - run:
          name: Authenticate with Docker Hub
          command: | 
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1}

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - say-hello:
          filters:
            branches:
              only: main